platform :ios, '13.0'

def capacitor_pods
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios', :modular_headers => true
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios', :modular_headers => true
end

target 'Plugin' do
  capacitor_pods
end

# Se hai test
target 'PluginTests' do
  capacitor_pods
end
